/*
 * generated by Xtext 2.33.0
 */
package org.xtext.example.mydsl.ui.tests;

import com.google.inject.Injector;
import org.eclipse.xtext.testing.IInjectorProvider;
import org.xtext.example.assign3.ui.internal.Assign3Activator;

public class Assign3UiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return Assign3Activator.getInstance().getInjector("org.xtext.example.mydsl.Assign3");
	}

}
