/*
 * generated by Xtext 2.33.0
 */
package org.xtext.example.mydsl.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class Assign3UiModule extends AbstractAssign3UiModule {

	public Assign3UiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
