/*
 * generated by Xtext 2.33.0
 */
package org.xtext.example.mydsl.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class Assign4UiModule extends AbstractAssign4UiModule {

	public Assign4UiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
