/*
 * generated by Xtext 2.33.0
 */
package org.xtext.example.mydsl.parser.antlr;

import com.google.inject.Inject;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import org.xtext.example.mydsl.parser.antlr.internal.InternalAssign5Parser;
import org.xtext.example.mydsl.services.Assign5GrammarAccess;

public class Assign5Parser extends AbstractAntlrParser {

	@Inject
	private Assign5GrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalAssign5Parser createParser(XtextTokenStream stream) {
		return new InternalAssign5Parser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "Model";
	}

	public Assign5GrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(Assign5GrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
