/*
 * generated by Xtext 2.33.0
 */
package org.xtext.example.mydsl.ui;

import com.google.inject.Injector;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;
import org.osgi.framework.FrameworkUtil;
import org.xtext.example.assign3.ui.internal.Assign3Activator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class Assign3ExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return FrameworkUtil.getBundle(Assign3Activator.class);
	}
	
	@Override
	protected Injector getInjector() {
		Assign3Activator activator = Assign3Activator.getInstance();
		return activator != null ? activator.getInjector(Assign3Activator.ORG_XTEXT_EXAMPLE_MYDSL_ASSIGN3) : null;
	}

}
