/*
 * generated by Xtext 2.33.0
 */
package org.xtext.example.mydsl;


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class Assign3RuntimeModule extends AbstractAssign3RuntimeModule {
}
