/*
 * generated by Xtext 2.33.0
 */
package org.xtext.example.mydsl;


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class Assign3StandaloneSetup extends Assign3StandaloneSetupGenerated {

	public static void doSetup() {
		new Assign3StandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}
