/*
 * generated by Xtext 2.33.0
 */
package org.xtext.example.mydsl.parser.antlr;

import com.google.inject.Inject;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import org.xtext.example.mydsl.parser.antlr.internal.InternalAssign3Parser;
import org.xtext.example.mydsl.services.Assign3GrammarAccess;

public class Assign3Parser extends AbstractAntlrParser {

	@Inject
	private Assign3GrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalAssign3Parser createParser(XtextTokenStream stream) {
		return new InternalAssign3Parser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "Model";
	}

	public Assign3GrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(Assign3GrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
