/*
 * generated by Xtext 2.33.0
 */
package org.xtext.example.mydsl.ui.tests;

import com.google.inject.Injector;
import org.eclipse.xtext.testing.IInjectorProvider;
import org.xtext.example.assign4.ui.internal.Assign4Activator;

public class Assign4UiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return Assign4Activator.getInstance().getInjector("org.xtext.example.mydsl.Assign4");
	}

}
