/*
 * generated by Xtext 2.33.0
 */
package org.xtext.example.mydsl.validation;

import org.eclipse.xtext.validation.Check;

import pt.isep.enorm.atb.cr2.Feature;
import pt.isep.enorm.atb.cr2.Model;
import pt.isep.enorm.atb.cr2.Review;
import pt.isep.enorm.atb.cr2.Subject;

/**
 * This class contains custom validation rules. 
 *
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
public class MyDslValidator extends AbstractMyDslValidator {
	
	public static final String INVALID_NAME = "invalidName";
	
	@Check
	public void checkModelStartsWithCapital(Model model) {
		if (!Character.isUpperCase(model.getName().charAt(0))) {
			warning("Model name should start with a capital", getCurrentObject().eClass().eContainingFeature());
		}
	}
	
	@Check
	public void checkSubjectStartsWithCapital(Subject subject) {
		if (!Character.isUpperCase(subject.getName().charAt(0))) {
			warning("Subject name should start with a capital", getCurrentObject().eClass().eContainingFeature());
		}
	}
	
	@Check
	public void checkFeatureStartsWithCapital(Feature feature) {
		if (!Character.isUpperCase(feature.getName().charAt(0))) {
			warning("Review name should start with a capital", getCurrentObject().eClass().eContainingFeature());
		}
	}
	
	@Check
	public void checkReviewStartsWithCapital(Review review) {
		if (!Character.isUpperCase(review.getName().charAt(0))) {
			warning("Review name should start with a capital", getCurrentObject().eClass().eContainingFeature());
		}
	}
}
