/*
 * generated by Xtext 2.33.0
 */
package org.xtext.example.mydsl.validation;

import org.eclipse.xtext.validation.Check;

import pt.isep.enorm.atb.cr2.Feature;
import pt.isep.enorm.atb.cr2.Model;
import pt.isep.enorm.atb.cr2.Subject;
import pt.isep.enorm.atb.cr2.Cr2Package;

/**
 * This class contains custom validation rules. 
 *
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
public class Assign3Validator extends AbstractAssign3Validator {
	
	public static final String MODEL_NAME_CAPITAL = "Model name should start with a capital.";
	public static final String SUBJECT_NAME_CAPITAL = "Subject name should start with a capital.";
	public static final String FEATURE_NAME_CAPITAL = "Feature name should start with a capital.";
	
	@Check
	public void checkModelStartsWithCapital(Model model) {
		if (!Character.isUpperCase(model.getName().charAt(0))) {
			error(MODEL_NAME_CAPITAL, Cr2Package.Literals.MODEL__NAME, MODEL_NAME_CAPITAL);
		}
	}
	
	@Check
	public void checkSubjectStartsWithCapital(Subject subject) {
		if (!Character.isUpperCase(subject.getName().charAt(0))) {
			error(SUBJECT_NAME_CAPITAL, Cr2Package.Literals.SUBJECT__NAME, SUBJECT_NAME_CAPITAL);
		}
	}
	
	@Check
	public void checkFeatureStartsWithCapital(Feature feature) {
		if (!Character.isUpperCase(feature.getName().charAt(0))) {
			error(FEATURE_NAME_CAPITAL, Cr2Package.Literals.FEATURE__NAME, FEATURE_NAME_CAPITAL);
		}
	}
}
